---
deployment:
  tasks:
    - export CLIENT_PATH=/home/digital3/registration.sorted.berlin/client
    - cd $CLIENT_PATH
    - npm install
    - npm build

    - export SERVER_PATH=/home/digital3/registration.sorted.berlin/backend
    - cd $SERVER_PATH
    - npm install
    - npm start
