---
deployment:
  tasks:
    - export CLIENT_PATH=/home/digital3/registration.sorted.berlin/client
    - /bin/cd $CLIENT_PATH
    - /usr/local/bin/yarn install
    - /usr/local/bin/yarn build

    - export SERVER_PATH=/home/digital3/registration.sorted.berlin/backend
    - /bin/cd $SERVER_PATH
    - /usr/local/bin/yarn install
    - /usr/local/bin/yarn start
