---
deployment:
  tasks:
    - export CLIENT_PATH=/home/digital3/registration.sorted.berlin/client
    - cd $CLIENT_PATH
    - yarn install
    - yarn build

    - export SERVER_PATH=/home/digital3/registration.sorted.berlin/backend
    - cd $SERVER_PATH
    - yarn install
    - yarn start
